import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

const myCustomFont = localFont({
	src: [
		{
			path: "../public/fonts/Ubuntu-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../public/fonts/Ubuntu-Medium.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/Ubuntu-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "../public/fonts/Ubuntu-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		// Add more font variations (italic, different weights) as needed
	],
	display: "swap",
	variable: "--font-ubuntu",
});

import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${myCustomFont.variable} ${geistSans.variable} ${geistMono.variable}`}>{children}</body>
		</html>
	);
}
